### ISSUE TITLE
Roblox Studio LocalScript Compiler

### ISSUE THREAD

**Issue by Scuffered** [rsblox/local_rcc#15]
I wonder if I can do same to join to game from Roblox Studio to local rcc on my another pc. But when I try to do that it gives me error about bytecodes in local scripts, so I wonder if I could do same as you did `Lua::compiler` hook for server but for client.

I injected DLL to client but I'm not sure that it is even possible with that DLL..

**Comment by 7ap** [comment]
> to join to game from Roblox Studio to local rcc on my another pc

The easiest way of doing this would be to not patch the `generateSchemaDefinitionPacket` function on the server, as Studio already expects `ProtectedStringSource`.

> I wonder if I could do same as you did Lua::compiler hook for server but for client

If you want to execute bytecode compiled with `LuaVM::BytecodeEncoderClient`, you could hook `luau_load` and reverse what local_rcc's `LuaVM::compile` hook does to the bytecode.

> I injected DLL to client but I'm not sure that it is even possible with that DLL..

local_rcc is only supposed to be injected into the server only.
