### ISSUE TITLE
Patched RBX::Network::NetworkSchema::typeForProperty

### ISSUE THREAD

**Issue by wappbad** [rsblox/local_rcc#16]
Hi, i found a problem with `NetworkSchema::typeForProperty`. And i don't know how to fix this?

I use DLL Injector and Roblox Studio Mod Manager.

Here the output of the DLL Injector :

```
Hello, world!
Found compile
Found deserialize_item
Found type_for_property_mov_imm_address
Scanning finished.
Hooked LuaVM::compile.
Hooked RBX::Network::Replicator::deserializeItem.
Patched RBX::Network::NetworkSchema::typeForProperty.
Made with <3 by 7ap & Epix @ https://github.com/rsblox - come join us!
```
And nothing happen when I start the server.

Can you help me? I will try to respond as quickly as possible. THANKS

**Comment by 7ap** [comment]
Hi, local_rcc has been patched - we are not offering support anymore.
