### ISSUE TITLE
Question about project

### ISSUE THREAD

**Issue by pyromixLua** [rsblox/local_rcc#18]
Hey, I'm very interested in this project and I was waiting for it!

I successful to compile the project in "`.dll`" but, I had a lot of trouble understanding why it doesn't work after opening **Roblox Studio** and injecting and testing it.

Basically, I had errors in the **Roblox Studio client test** saying: "`bytecode version mismatch (expected [3..6] ...)`"

Can you explain me how I can solve it?

And if possible to connect with the **Roblox Player**?

Thanks !

**Comment by 7ap** [comment]
Hi, thanks for taking interest in the project!

With local_rcc's DLL injected into a Studio server, it will cause problems for Studio clients trying to connect. Think of this as what's happening [here](https://github.com/rsblox/local_rcc#networkschema), just the other way around. You either can have Studio clients connect (don't inject local_rcc's DLL) or could have had Player clients connect.

Unfortunately, Roblox has pushed a patch a few months ago and local_rcc is no longer functional. We are no longer providing support for it. I keep forgetting to write a notice about that (sorry!), I'll get to it soon.
