### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by stan2474** [rsblox/local_rcc#2]
text file doesn’t run

**Comment by regginator** [comment]
skill. Issue

**Comment by httpget** [comment]
why not

**Comment by 6zip** [comment]
edit: fixed!

**Comment by gtoriadotnet** [comment]
@7ap @stan2474 @regginator @httpget @6zip @EpixScripts big issue please fix

**Comment by 7ap** [comment]
I'll work on getting the launcher and a GitHub workflow up tomorrow.

**Comment by stan2474** [comment]
one more fucking dislike and I’ll release a cheat that will CRASH local_rcc… Pick and choose

**Comment by krampuscg** [comment]
@brose broke the build!
⚠️ failures blah blah blah

**Comment by EpixScripts** [comment]
still isn't running

**Comment by WaviestBalloon** [comment]
> text file doesn’t run

Rewriting in Rust would fix this

**Comment by httpget** [comment]
> > text file doesn’t run
> 
> Rewriting in Rust would fix this

truth

**Comment by MakeSureDudeDies** [comment]
> > text file doesn’t run
> 
> Rewriting in Rust would fix this

rust is the future and the future is now

**Comment by 7ap** [comment]
> I'll work on getting the launcher and a GitHub workflow up tomorrow.

Build instructions were added.

**Comment by krampuszc** [comment]
> > text file doesn’t run
> 
> Rewriting in Rust would fix this

rust would not fix this. Rust is nsa spyware.

**Comment by icymanred** [comment]
> > > text file doesn’t run
> > 
> > 
> > Rewriting in Rust would fix this
> 
> rust would not fix this. Rust is nsa spyware.

pine wood sucks innovation inc betta

**Comment by httpget** [comment]
is it still broken

**Comment by Robox-Corporation** [comment]
> is it still broken

at least from my last test like 10 days ago it still works, (in fact it has still technically worked ever since the networkclient refactor)
you just gotta use a proxy like fiddler on roblox in order to change the joinscript to your local server, then change the raknet password on studio to player's (so that they match and you dont get invalid password)

**Comment by BigMark824** [comment]
thank you roblox corporation
