### ISSUE TITLE
Join local RCC from mobile

### ISSUE THREAD

**Issue by grilme99** [rsblox/local_rcc#9]
This project is really cool!

Something I've been wanting to investigate for a while is improving the debug tools available when testing games on mobile. Theoretically, if you can connect a mobile client to this local RCC server, then it should be possible to pipe debug info over the network to visualise in Studio without any HTTP hacks. This might also enable things like hot reloading client code on mobile.

What work would be required to get mobile clients connected to local RCC? It looks like it just needs a flag flip. Has there been any exploratory work done already on how to flip flags on mobile? I'm also not sure if mobile clients would be able to connect to localhost out of the box.

Very excited for this! Hopefully it isn't patched by Roblox.

**Comment by grilme99** [comment]
Also, is there a Discord server being used to discuss this project?

**Comment by crossliner** [comment]
> Also, is there a Discord server being used to discuss this project?

Yes, http://discord.gg/s6rw3k7vKT

**Comment by Halal-Dev** [comment]
![image](https://github.com/rsblox/local_rcc/assets/54723649/07ea9b39-92ce-4fe0-b0f1-01ddc04f933a)

**Comment by genericmicrosoftlover** [comment]
> ![image](https://private-user-images.githubusercontent.com/54723649/314542656-07ea9b39-92ce-4fe0-b0f1-01ddc04f933a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDc2MTQsIm5iZiI6MTcxMTA0NzMxNCwicGF0aCI6Ii81NDcyMzY0OS8zMTQ1NDI2NTYtMDdlYTliMzktOTJjZS00ZmUwLWIwZjEtMDFkZGMwNGY5MzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE4NTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZjRhMTAwMDJjYTRiYWNhYzIzYjc1YzdkMjNjYWRjYTlhYTcyYmRiYzQzMDUwZDk3YmIxOTc1NjJhMmVjYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JkSVSu8ytucwADivz-f4KxLQi_WkX_fCiZp7qDdQ7gY)

get your damn pterodactyl hands off that samsung s5

**Comment by spidercraft** [comment]
how did you change the flag on a mobile device lol

**Comment by 7ap** [comment]
Resolved via Discord.

**Comment by Windows81** [comment]
@spidercraft:

On Windows (versions 623 and older), Rōblox sends an HTTPS request to fetch your flags.  The file `./ClientSettings/ClientAppSettings.json` would overwrite the flags which you have set.

My assumption is that he set a man-in-the-middle proxy on his phone to change the FFlags which are loaded by the Rōblox web server.

I hope this answers your question.
